### ISSUE TITLE
Email dont work

### ISSUE THREAD

**Issue by vitorgamer58** [InfraexDev/peatio#107]
i get this error
```
I, [2018-06-20T21:35:10.486477 #5728]  INFO -- : Received: {"mailer_class":"TokenMailer","method":"activation","args":["vitorgamer58@gmail.com","d8e6f5c51c21f7bd51aa3c1e9c7858cb"],"locale":"en"}
F, [2018-06-20T21:35:20.518125 #5728] FATAL -- : end of file reached (EOFError)
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/smtp.rb:945:in `recv_response'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/smtp.rb:555:in `block in do_start'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/smtp.rb:955:in `critical'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/smtp.rb:555:in `do_start'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/actionmailer-4.0.12/lib/action_mailer/base.rb:456:in `block in deliver_mail'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/notifications.rb:159:in `block in instrument'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/notifications.rb:159:in `instrument'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/actionmailer-4.0.12/lib/action_mailer/base.rb:454:in `deliver_mail'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
/home/deploy/peatio/current/app/models/worker/email_notification.rb:13:in `process'
/home/deploy/peatio/current/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'

```

my config
```
  SMTP_PORT: 465
  SMTP_DOMAIN: brexchange.br-com.net
  SMTP_ADDRESS: smtp.gmail.com
  SMTP_USERNAME: brexchange.noreply
  SMTP_PASSWORD: ********
  SMTP_AUTHENTICATION:
```

**Comment by vitorgamer58** [comment]
solved with

```
  SMTP_PORT: 587
  SMTP_DOMAIN: gmail.com
  SMTP_ADDRESS: smtp.gmail.com
  SMTP_USERNAME: brexchange.noreply
  SMTP_PASSWORD: ********
  SMTP_AUTHENTICATION: plain
```
and 
```
  config.action_mailer.smtp_settings = {
    port:           ENV["SMTP_PORT"],
    domain:         ENV["SMTP_DOMAIN"],
    address:        ENV["SMTP_ADDRESS"],
    user_name:      ENV["SMTP_USERNAME"],
    password:       ENV["SMTP_PASSWORD"],
    authentication: ENV["SMTP_AUTHENTICATION"],
    enable_starttls_auto: true
  }
```
