### ISSUE TITLE
ActionView::Template::Erro (Couldn't load the Unicode tables for UTF8Handler (dump format error(0x72)),    admin dashboard issue 

### ISSUE THREAD

**Issue by AnthonyRex** [InfraexDev/peatio#139]
I got this when i click on bitcoin deposit or members or anything which having transactions  to show .  the pages with no transactions i can access. but when there is a transactions to display  I am getting  the same errors 
https://mydomain.com/admin/deposits/satoshis
and 

this is the log  for btc deposit page and members page in the admin 

1---   bitcoin deposit  log or any log with transaction to show

I, [2018-10-28T10:45:56.563047 #21087]  INFO -- : Started GET "/admin/deposits/satoshis" for 175.136.62.121 at 2018-10-28 10:45:56 +0000
I, [2018-10-28T10:45:56.575252 #21087]  INFO -- : Processing by Admin::Deposits::SatoshisController#index as HTML
I, [2018-10-28T10:45:56.873325 #21087]  INFO -- :   Rendered admin/deposits/satoshis/index.html.slim within layouts/admin (180.1ms)
I, [2018-10-28T10:45:56.873636 #21087]  INFO -- : Completed 500 Internal Server Error in 298ms
F, [2018-10-28T10:45:56.876516 #21087] FATAL -- : 
ActionView::Template::Error (Couldn't load the Unicode tables for UTF8Handler (dump format error(0x72)), ActiveSupport::Multibyte is unusable):
    1: = table_for(@satoshis, class: 'table table-condensed table-hover') do |t|
    2:   - t.column :txid do |x|
    3:     a href='#{x.blockchain_url}' target='_blank'
    4:       code.text-info = x.txid.truncate(36)
  app/views/admin/deposits/satoshis/index.html.slim:1:in `_app_views_admin_deposits_satoshis_index_html_slim__4383426742398496761_47376430201140'
  lib/middleware/security.rb:11:in `call'

2 -----members page 
https://mydomain.com//admin/members

I, [2018-10-28T10:45:54.213517 #23157]  INFO -- : {"jsonrpc"=>"2.0", "id"=>"1", "result"=>"0x316efa"}
I, [2018-10-28T10:45:54.218247 #21087]  INFO -- :   Rendered admin/members/index.html.slim within layouts/admin (180.0ms)
I, [2018-10-28T10:45:54.219130 #21087]  INFO -- : Completed 500 Internal Server Error in 245ms
F, [2018-10-28T10:45:54.224168 #21087] FATAL -- : 
ActionView::Template::Error (Couldn't load the Unicode tables for UTF8Handler (dump format error(0x72)), ActiveSupport::Multibyte is unusable):
    18:     .panel-heading
    19:       span = t('.members')
    20:     .panel-body                     
    21:       = table_for(@members, class: 'table table-condensed table-hover') do |t|
    22:         - t.column :id, class: 'col-xs-1'
    23:         - t.column :email, class: 'col-xs-2' do |x|
    24:           code.text-info = x.email
  app/views/admin/members/index.html.slim:21:in `_app_views_admin_members_index_html_slim__2181630766757966780_47376434463540'
  lib/middleware/security.rb:11:in `call'

exactly the same issue causing this  
I hope I can get  help to solve this issue

**Comment by AnthonyRex** [comment]
solved
