### ISSUE TITLE
NoMethodError: undefined method `set_default' for main:Object

### ISSUE THREAD

**Issue by dutchakdev** [InfraexDev/peatio#2]
Hey! First, thank you for contributing and support this awesome project.

I have some issues with install:

```
ex master ✗ 5d △ ◒ ➜ bundle exec rake db:setup --trace
rake aborted!
NoMethodError: undefined method `set_default' for main:Object
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/mina-slack-0.1.0/lib/mina/slack/defaults.rb:2:in `<top (required)>'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/mina-slack-0.1.0/lib/mina/slack.rb:3:in `<top (required)>'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:95:in `require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:95:in `rescue in block in require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:72:in `block in require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/dutchakdev/newage/ex/config/application.rb:12:in `<top (required)>'
/Users/dutchakdev/newage/ex/Rakefile:5:in `require'
/Users/dutchakdev/newage/ex/Rakefile:5:in `<top (required)>'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:82:in `block in run'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/bin/rake:23:in `load'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/bin/rake:23:in `<main>'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
LoadError: cannot load such file -- mina-slack
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/dutchakdev/newage/ex/config/application.rb:12:in `<top (required)>'
/Users/dutchakdev/newage/ex/Rakefile:5:in `require'
/Users/dutchakdev/newage/ex/Rakefile:5:in `<top (required)>'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:82:in `block in run'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/bin/rake:23:in `load'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/bin/rake:23:in `<main>'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/dutchakdev/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
ex master ✗ 5d △ ◒ ⍉```

**Comment by dutchakdev** [comment]
also i use `gem 'mina-slack'` becouse repo `peatio/mina-slack` was disabled

**Comment by muhammednagy** [comment]
Fixed ! :)
