### ISSUE TITLE
[Sign up] Errno::EADDRNOTAVAIL (Cannot assign requested address - connect(2) for nil port 25):

### ISSUE THREAD

**Issue by dutchakdev** [InfraexDev/peatio#21]
Have some problem when user register:
```
Errno::EADDRNOTAVAIL (Cannot assign requested address - connect(2) for nil port 25):
  app/models/amqp_queue.rb:94:in `deliver!'
  app/models/amqp_queue.rb:88:in `rescue in deliver'
  app/models/amqp_queue.rb:84:in `deliver'
  app/models/token/activation.rb:12:in `send_token'
  app/models/member.rb:184:in `send_activation'
  app/models/member.rb:95:in `create_from_auth'
  app/models/member.rb:41:in `from_auth'
  app/controllers/sessions_controller.rb:16:in `create'
  lib/middleware/security.rb:11:in `call'
```

**Comment by muhammednagy** [comment]
do you have the email configured?
in application.yml 
are the daemons running?
is rabbitmq up and running?

**Comment by dutchakdev** [comment]
All ok, my friend, i working on dockerization and made a mistake in the link of containers
