### ISSUE TITLE
deposit fiat funds ( set default bank account) Fatal Error

### ISSUE THREAD

**Issue by mrtass** [InfraexDev/peatio#22]
Hi i'm having issue setting default Bank Account:
production.log show below error:
```
F, [2018-02-13T10:04:42.991543 #5942] FATAL -- :
ActiveRecord::AssociationTypeMismatch (FundSource(#46982052885740) expected, got String(#46982022629240)):
  app/controllers/private/fund_sources_controller.rb:17:in `update'
  lib/middleware/security.rb:11:in `call'
```
Anyone experiencing That ?

**Comment by muhammednagy** [comment]
Resolved now?
