### ISSUE TITLE
Deposit ETH not showing in balance

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#57]
Reopen this issue:

Hi, Muhammednagy,

I have deposited some ETH to the account, it is verified on etherscan.io but does not show up in the peatio ETH account balance.

I have followed the instruction setting up ETH server and have no problem generating ETH address for deposit.

Thanks.

on ETH server,

service filter status
● filter.service - filter
Loaded: loaded (/etc/systemd/system/filter.service; enabled; vendor preset: enabled)
Active: active (running) since Sun 2018-03-18 19:18:54 UTC; 5h 32min ago
Main PID: 12128 (ruby)
Tasks: 10
Memory: 31.4M
CPU: 3h 36min 34.566s
CGroup: /system.slice/filter.service
└─12128 /usr/bin/ruby /home/xxx/service.rb

Does that mean service.rb is working?

in service.rb:
postData = Net::HTTP.post_form(URI.parse('https://exchangexx.com/webhooks/eth'),.......

Problem still not resolved though.

Thank you.

**Comment by auvilink** [comment]
The ETH deposit went through, butit just not showing in peatio's ETH account balance.

I checked peatio  production.log, everything seems fine:

I, [2018-03-22T04:34:07.415099 #14692]  INFO -- : Started POST "/webhooks/eth" for 159.65.141.137 at 2018-03-22 04:34:07 +0000
I, [2018-03-22T04:34:07.418866 #14692]  INFO -- : Processing by WebhooksController#eth as */*
I, [2018-03-22T04:34:07.418915 #14692]  INFO -- :   Parameters: {"type"=>"transaction", "hash"=>"0x6a422d9684f6d40e894d26cf9bf3523d1ff487f0d1016069d36e269ef93cfc8a"}
I, [2018-03-22T04:34:07.429080 #14692]  INFO -- : Completed 200 OK in 10ms (Views: 0.2ms | ActiveRecord: 0.9ms)

In peatio\:amqp\:deposit_coin.output, I found 

I, [2018-03-21T22:16:32.002976 #13822]  INFO -- : Connected to AMQP broker (prefetch: default)
I, [2018-03-22T04:34:07.428959 #13822]  INFO -- : Received: {"txid":"0x6a422d9684f6d40e894d26cf9bf3523d1ff487f0d1016069d36e269ef93cfc8a","channel_key":"ether","locale":"en"}
**## F, [2018-03-22T04:34:07.940402 #13822] FATAL -- : undefined method `symbolize_keys!' for nil:NilClass (NoMethodError)**
/home/deploy/peatio/current/app/models/worker/deposit_coin.rb:15:in `process'

This could be the reason, right?

**Comment by nantestdevoloper** [comment]
hi ,

I have added some btc to the deposit address of peatio, but not reflecting in account of user .
Bitcoind server is  sych .   Setup peatio on local ubuntu system .daemons are running .

deposit_coin.log as below

E, [2018-03-30T13:03:48.168716 #4083] ERROR -- : no such frame (ArgumentError)
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/.rvm/gems/ruby-2.2.1/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/session.rb:940:in `open_connection'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/session.rb:255:in `start'
/home/test/peatio/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/deposit_coin_ctl:11:in `<main>'
E, [2018-03-30T13:03:48.168877 #4083] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/session.rb:940:in `open_connection'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/session.rb:255:in `start'
/home/test/peatio/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/deposit_coin_ctl:11:in `<main>'
E, [2018-03-30T13:03:48.169001 #4083] ERROR -- : no such frame (ArgumentError)
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/.rvm/gems/ruby-2.2.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/.rvm/gems/ruby-2.2.1/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/session.rb:923:in `init_connection'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/session.rb:254:in `start'
/home/test/peatio/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/deposit_coin_ctl:11:in `<main>'
E, [2018-03-30T13:03:48.169073 #4083] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/session.rb:923:in `init_connection'
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/session.rb:254:in `start'
/home/test/peatio/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/.rvm/gems/ruby-2.2.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/deposit_coin_ctl:11:in `<main>'

**Comment by ninoara** [comment]
Having the same problem. please how do you fixed that?
