### ISSUE TITLE
Is this normal when running GETH

### ISSUE THREAD

**Issue by hostsleek** [InfraexDev/peatio#79]
Is this normal when running GETH command.

root@eth:~# geth
INFO [04-20|02:52:52] Maximum peer count                       ETH=25 LES=0 total=25
Fatal: Error starting protocol stack: datadir already used by another process

**Comment by hostsleek** [comment]
After updating coin_rpc.rb
Balance still does not reflect on the ETH balance.

Why do i get this

Fatal: Failed to start the JavaScript console: mkdir /var/www/.ethereum: permission denied

**Comment by muhammednagy** [comment]
execute this command 
sudo mkdir /var/www/.ethereum
also  this
Fatal: Error starting protocol stack: datadir already used by another process  
means that geth is already running by the service
try geth attach

**Comment by hostsleek** [comment]
Thanks.. After running sudo mkdir /var/www/.ethereum
I get below now.. 
Fatal: Failed to start the JavaScript console: api modules: Post http://127.0.0.1:8545: context deadline exceeded

I am still yet to see my sent ETH on my funds page.

Also ETH is installed on a separate server with user ROOT and not deploy..

**Comment by hostsleek** [comment]
I also get the below error when trying to withdraw BTC

```
Error on withdraw audit: CoinRPC::ConnectionRefusedError
/home/deploy/peatio/current/app/services/coin_rpc.rb:46:in `rescue in http_post_request'
/home/deploy/peatio/current/app/services/coin_rpc.rb:39:in `http_post_request'
/home/deploy/peatio/current/app/services/coin_rpc.rb:32:in `handle'
/home/deploy/peatio/current/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/current/app/models/concerns/withdraws/coinable.rb:14:in `audit!'
/home/deploy/peatio/current/lib/daemons/withdraw_audit.rb:19:in `block in <top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation/delegation.rb:13:in `each'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation/delegation.rb:13:in `each'
/home/deploy/peatio/current/lib/daemons/withdraw_audit.rb:17:in `<top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/withdraw_audit_ctl:6:in `<main>'
withdraw_audit.rb: process with pid 2087 started.
withdraw_audit.rb: process with pid 2346 started.
withdraw_audit.rb: process with pid 1951 started.
withdraw_audit.rb: process with pid 2433 started.
withdraw_audit.rb: process with pid 1979 started.

```
