### ISSUE TITLE
Compile and access to js/ss

### ISSUE THREAD

**Issue by dutchakdev** [InfraexDev/peatio#9]
After runing, db:setup and assets:precompile i see page without styles. 

In logs/productions.log:

```
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
  lib/middleware/security.rb:11:in `call'


F, [2018-02-09T18:48:32.709886 #742] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/javascripts/locales/en.js"):
  lib/middleware/security.rb:11:in `call'


F, [2018-02-09T18:48:32.709910 #554] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
  lib/middleware/security.rb:11:in `call'
```

**Comment by dutchakdev** [comment]
Fixed. 

`config.assets.compile = true`
